spring.application.name=Loyalty
spring.datasource.url=jdbc:mysql://localhost:3306/loyaltydb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Techtree@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true	

logging.file.name=log/log4j2.txt
logging.pattern.file= %d [%c] [%p] ---> %m [%M] %n

logging.level.com.reciproci.loyalty=debug